POST http://localhost:8080/api/dogs/7/owner
Content-Type: application/json

{
  "name": "Mila Kunis"
}

###

POST http://localhost:8080/api/dogs
Content-Type: application/json

{
  "name": "Ronnie",
  "breed": "bullDog",
  "age": 3
}

###

POST http://localhost:8080/api/dogs
Content-Type: application/json

{
  "name": "Liza",
  "breed": "Mops",
  "age": 2
}

###

PUT http://localhost:8080/api/dogs/8
Content-Type: application/json

{
  "name": "Lili",
  "breed": "Yorkie",
  "age": 3,
  "favToy": "Ball"
}

###

GET http://localhost:8080/api/dogs
Accept: application/json

###

GET http://localhost:8080/api/dogs/7
Accept: application/json

###

DELETE http://localhost:8080/api/dogs/2

###

DELETE http://localhost:8080/api/dogs