PUT http://localhost:8080/api/owners/6
Content-Type: application/json

{
  "name": "Anne Hathawy"
}

###

PUT http://localhost:8080/api/owners/6/dogs
Content-Type: application/json

{
  "id": 7
}

###

POST http://localhost:8080/api/owners/6/dogs
Content-Type: application/json

{
  "name": "Lili",
  "breed": "mopps",
  "age": 2
}

###

POST http://localhost:8080/api/owners
Content-Type: application/json

{
  "name": "Margot Robbie"
}

###

GET http://localhost:8080/api/owners/4
Accept: application/json

###

GET http://localhost:8080/api/owners
Accept: application/json

###

DELETE http://localhost:8080/api/owners

###

DELETE http://localhost:8080/api/owners/5
